spring.application.name=chronicles-api

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/chronicles_db
spring.datasource.username=chronicles_user
spring.datasource.password=chronicles_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration